# Generated by Django 3.2.5 on 2021-08-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_moreproductimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='product_price',
            field=models.CharField(default='', max_length=100),
        ),
    ]
