# Generated by Django 3.2.5 on 2021-08-03 08:14

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_reviewsorderable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=wagtail.core.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='reviewsorderable',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutus.review'),
        ),
    ]
