# Generated by Django 3.2.5 on 2021-08-03 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('aboutus', '0003_auto_20210803_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuspage',
            name='hero_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
