# Generated by Django 3.2.5 on 2021-07-29 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productpage'),
        ('home', '0003_auto_20210728_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productpage'),
        ),
    ]
