# Generated by Django 3.2.5 on 2021-07-29 19:07

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productpage'),
        ('home', '0004_homepage_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='featured',
        ),
        migrations.AddField(
            model_name='homepage',
            name='featureds',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='product.ProductPage'),
        ),
    ]
