# Generated by Django 3.2.5 on 2021-08-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_promotionslistpage_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionpage',
            name='promotion_short_text',
            field=models.CharField(default='', max_length=300),
        ),
    ]
